# Generated by Django 4.2.28 on 2026-02-16 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatedCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=64, unique=True)),
                ('day_summary', models.TextField(blank=True)),
                ('favorite_foods', models.JSONField(default=list)),
                ('dietary_label', models.CharField(choices=[('omnivore', 'omnivore'), ('vegetarian', 'vegetarian'), ('vegan', 'vegan')], default='omnivore', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SimulatedConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chatbot.simulatedcustomer')),
            ],
        ),
        migrations.CreateModel(
            name='SimulatedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('waiter', 'waiter'), ('customer', 'customer')], max_length=16)),
                ('content', models.TextField()),
                ('turn_index', models.PositiveIntegerField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.simulatedconversation')),
            ],
            options={
                'ordering': ['turn_index'],
                'unique_together': {('conversation', 'turn_index')},
            },
        ),
    ]
