# Generated by Django 4.2.28 on 2026-02-16 23:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulatedcustomer',
            name='day_summary',
        ),
        migrations.RemoveField(
            model_name='simulatedcustomer',
            name='favorite_foods',
        ),
        migrations.AddField(
            model_name='simulatedconversation',
            name='customer_transcript',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='simulatedconversation',
            name='ordered_dishes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='simulatedconversation',
            name='waiter_transcript',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='simulatedcustomer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulatedcustomer',
            name='favourite_food_1',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='simulatedcustomer',
            name='favourite_food_2',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='simulatedcustomer',
            name='favourite_food_3',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='simulatedcustomer',
            name='dietary_label',
            field=models.CharField(choices=[('omnivore', 'Omnivore'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan')], default='omnivore', max_length=16),
        ),
        migrations.DeleteModel(
            name='SimulatedMessage',
        ),
    ]
