# Generated by Django 4.2.28 on 2026-02-16 23:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_remove_simulatedcustomer_day_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulatedconversation',
            name='customer_transcript',
        ),
        migrations.RemoveField(
            model_name='simulatedconversation',
            name='waiter_transcript',
        ),
        migrations.RemoveField(
            model_name='simulatedcustomer',
            name='favourite_food_1',
        ),
        migrations.RemoveField(
            model_name='simulatedcustomer',
            name='favourite_food_2',
        ),
        migrations.RemoveField(
            model_name='simulatedcustomer',
            name='favourite_food_3',
        ),
        migrations.AddField(
            model_name='simulatedconversation',
            name='session_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulatedcustomer',
            name='favorite_foods',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='simulatedconversation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='simulatedcustomer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='SimulatedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('waiter', 'Waiter'), ('customer', 'Customer')], max_length=16)),
                ('content', models.TextField()),
                ('turn_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.simulatedconversation')),
            ],
            options={
                'ordering': ['turn_index', 'id'],
            },
        ),
    ]
