# Generated by Django 4.2.28 on 2026-02-16 23:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_simulatedconversation_customer_transcript_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simulatedmessage',
            options={},
        ),
        migrations.RemoveField(
            model_name='simulatedmessage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='simulatedcustomer',
            name='day_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='simulatedconversation',
            name='session_code',
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True),
        ),
    ]
