# Generated by Django 4.2.28 on 2026-03-01 21:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_simulatedmessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatedEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=64, unique=True)),
                ('department', models.CharField(blank=True, default='', max_length=64)),
                ('role_title', models.CharField(blank=True, default='', max_length=128)),
                ('seniority', models.CharField(choices=[('junior', 'Junior'), ('medior', 'Medior'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager')], default='medior', max_length=16)),
                ('persona_notes', models.TextField(blank=True, default='')),
                ('work_context_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SimulatedInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_context', models.JSONField(blank=True, default=dict)),
                ('question_target', models.PositiveIntegerField(default=5)),
                ('improvement_opportunities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='chatbot.simulatedemployee')),
            ],
        ),
        migrations.CreateModel(
            name='SimulatedInterviewMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('interviewer', 'Interviewer'), ('employee', 'Employee')], max_length=16)),
                ('content', models.TextField()),
                ('turn_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.simulatedinterview')),
            ],
            options={
                'indexes': [models.Index(fields=['interview', 'turn_index'], name='chatbot_sim_intervi_c36019_idx'), models.Index(fields=['role'], name='chatbot_sim_role_77f68c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='simulatedinterviewmessage',
            constraint=models.UniqueConstraint(fields=('interview', 'turn_index'), name='uniq_interview_turn'),
        ),
    ]
