# Generated by Django 4.2.28 on 2026-03-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_simulatedemployee_simulatedinterview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardInsightRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('n_interviews', models.PositiveIntegerField(default=0)),
                ('top_recommendation', models.TextField(blank=True, default='')),
                ('themes', models.JSONField(blank=True, default=list)),
                ('method_metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
