# Generated by Django 4.2.28 on 2026-03-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_boardinsightrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinsightrun',
            name='top_recommendation',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
