# Generated by Django 4.2.28 on 2026-03-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_alter_boardinsightrun_top_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulatedinterview',
            name='improvement_opportunities',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
